//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Honcho.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Honcho.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Taking a Break:.
        /// </summary>
        internal static string BadgererDisplayOptionsGroupBoxText {
            get {
                return ResourceManager.GetString("BadgererDisplayOptionsGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Badgerer Window as:.
        /// </summary>
        internal static string BadgererWindowDisplayLabel {
            get {
                return ResourceManager.GetString("BadgererWindowDisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximized normal window.
        /// </summary>
        internal static string BadgererWindowMaximizedText {
            get {
                return ResourceManager.GetString("BadgererWindowMaximizedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overlay window.
        /// </summary>
        internal static string BadgererWindowOverlayText {
            get {
                return ResourceManager.GetString("BadgererWindowOverlayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unmaximized normal window.
        /// </summary>
        internal static string BadgererWindowUnmaximizedText {
            get {
                return ResourceManager.GetString("BadgererWindowUnmaximizedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a Break for.
        /// </summary>
        internal static string BreakDurationLabelText {
            get {
                return ResourceManager.GetString("BreakDurationLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a Break Every.
        /// </summary>
        internal static string BreakIntervalLabelText {
            get {
                return ResourceManager.GetString("BreakIntervalLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Length and Interval:.
        /// </summary>
        internal static string BreakOptionsGroupBoxText {
            get {
                return ResourceManager.GetString("BreakOptionsGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Taking Breaks.
        /// </summary>
        internal static string BreakRepeatLabelText {
            get {
                return ResourceManager.GetString("BreakRepeatLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daily:.
        /// </summary>
        internal static string BreakScheduleDailyText {
            get {
                return ResourceManager.GetString("BreakScheduleDailyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every number of days:.
        /// </summary>
        internal static string BreakScheduleEveryNumberOfDaysText {
            get {
                return ResourceManager.GetString("BreakScheduleEveryNumberOfDaysText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indefinitely..
        /// </summary>
        internal static string BreakScheduleIndefinitelyText {
            get {
                return ResourceManager.GetString("BreakScheduleIndefinitelyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Breaks to Happen.
        /// </summary>
        internal static string BreakScheduleLabelText {
            get {
                return ResourceManager.GetString("BreakScheduleLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on certain days of the week:.
        /// </summary>
        internal static string BreakScheduleOnCertainDaysOfTheWeekText {
            get {
                return ResourceManager.GetString("BreakScheduleOnCertainDaysOfTheWeekText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Taking Breaks.
        /// </summary>
        internal static string BreakStartLabelText {
            get {
                return ResourceManager.GetString("BreakStartLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the end of time..
        /// </summary>
        internal static string BreakUntilIndefinitelyText {
            get {
                return ResourceManager.GetString("BreakUntilIndefinitelyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Scheduling Breaks Until.
        /// </summary>
        internal static string BreakUntilLabelText {
            get {
                return ResourceManager.GetString("BreakUntilLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a specific duration has passed:.
        /// </summary>
        internal static string BreakUntilSpecificDurationText {
            get {
                return ResourceManager.GetString("BreakUntilSpecificDurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a specific time:.
        /// </summary>
        internal static string BreakUntilSpecificTimeText {
            get {
                return ResourceManager.GetString("BreakUntilSpecificTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string ExitMenuName {
            get {
                return ResourceManager.GetString("ExitMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Name.
        /// </summary>
        internal static string FriendlyNameLabelText {
            get {
                return ResourceManager.GetString("FriendlyNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon HonchoIcon {
            get {
                object obj = ResourceManager.GetObject("HonchoIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzu Honcho.
        /// </summary>
        internal static string HonchoToolTip {
            get {
                return ResourceManager.GetString("HonchoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock the screen.
        /// </summary>
        internal static string LockScreenCheckboxText {
            get {
                return ResourceManager.GetString("LockScreenCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for a certain number of times:.
        /// </summary>
        internal static string RepeatAmountCertainNumberOfTimesText {
            get {
                return ResourceManager.GetString("RepeatAmountCertainNumberOfTimesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indefinitely..
        /// </summary>
        internal static string RepeatAmountIndefinitelyText {
            get {
                return ResourceManager.GetString("RepeatAmountIndefinitelyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only once..
        /// </summary>
        internal static string RepeatAmountOnceText {
            get {
                return ResourceManager.GetString("RepeatAmountOnceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for a certain duration:.
        /// </summary>
        internal static string RepeatAmountUntilCertainDurationText {
            get {
                return ResourceManager.GetString("RepeatAmountUntilCertainDurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until a specific time: .
        /// </summary>
        internal static string RepeatAmountUntilSpecificTimeText {
            get {
                return ResourceManager.GetString("RepeatAmountUntilSpecificTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule &amp;new break....
        /// </summary>
        internal static string ScheduleNewBreakMenuName {
            get {
                return ResourceManager.GetString("ScheduleNewBreakMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule New Break.
        /// </summary>
        internal static string ScheduleNewBreakTitleBarText {
            get {
                return ResourceManager.GetString("ScheduleNewBreakTitleBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling Options:.
        /// </summary>
        internal static string ScheduleOptionsGroupBoxText {
            get {
                return ResourceManager.GetString("ScheduleOptionsGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after the hour at: .
        /// </summary>
        internal static string StartingTimeAfterTheHourText {
            get {
                return ResourceManager.GetString("StartingTimeAfterTheHourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now..
        /// </summary>
        internal static string StartingTimeNowText {
            get {
                return ResourceManager.GetString("StartingTimeNowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at a specific time:.
        /// </summary>
        internal static string StartingTimeSpecificTimeText {
            get {
                return ResourceManager.GetString("StartingTimeSpecificTimeText", resourceCulture);
            }
        }
    }
}
